# Generated by Django 5.0.1 on 2025-03-12 03:54

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keysGen', '0002_license_expiration_date_license_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='key',
        ),
        migrations.AddField(
            model_name='license',
            name='serial_number',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 3, 54, 35, 45751, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
