# Generated by Django 5.0.1 on 2025-03-13 16:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keysGen', '0003_remove_license_key_license_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
