# Generated by Django 5.0.1 on 2025-02-23 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_fcm_token'),
        ('keysGen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='keysGen.license'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='keysGen.license'),
        ),
        migrations.DeleteModel(
            name='License',
        ),
    ]
