# Generated by Django 5.0.1 on 2025-02-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_subscription_license_alter_payment_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Étudiant'), ('teacher', 'Professeur'), ('parent', 'Parent'), ('admin', 'Administrateur')], default='student', max_length=10),
        ),
    ]
