# Generated by Django 5.0.1 on 2025-02-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.ManyToManyField(blank=True, to='core.video'),
        ),
    ]
