# Generated by Django 5.0.1 on 2025-02-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_video_course_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audios/')),
            ],
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
        migrations.RemoveField(
            model_name='course',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='course',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video_file',
        ),
        migrations.AddField(
            model_name='course',
            name='audio_file',
            field=models.ManyToManyField(blank=True, to='core.audio'),
        ),
        migrations.AddField(
            model_name='course',
            name='pdf_file',
            field=models.ManyToManyField(blank=True, to='core.pdf'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_file',
            field=models.ManyToManyField(blank=True, to='core.video'),
        ),
    ]
