# Generated by Django 5.0.1 on 2025-02-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_audio_pdf_remove_course_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exercices/')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='exo_files',
            field=models.ManyToManyField(blank=True, to='core.exo'),
        ),
    ]
