# Generated by Django 5.0.1 on 2025-02-27 07:50

import core.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_exo_exercise_exo_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilepayment',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format international.', regex='^\\+?[0-9]{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storage.SecureFileStorage(), upload_to='resources/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'mp4', 'mp3'], message='Seuls les fichiers PDF, MP4 et MP3 sont autorisés.')]),
        ),
    ]
