# Generated by Django 5.0.1 on 2025-02-27 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_mobilepayment_phone_number_alter_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilepayment',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='provider',
            field=models.CharField(choices=[('ligdicash', 'LigdiCash'), ('orange', 'Orange Money'), ('mtn', 'MTN Mobile Money')], max_length=20),
        ),
    ]
