# Generated by Django 5.0.1 on 2025-03-08 10:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mobilepayment_user_alter_mobilepayment_provider'),
        ('keysGen', '0002_license_expiration_date_license_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilepayment',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format international.', regex='^\\+?[0-9]{9,15}$')]),
        ),
        migrations.CreateModel(
            name='LicensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('new', 'New License'), ('renew', 'Renew License')], max_length=20)),
                ('duration_months', models.IntegerField()),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keysGen.license')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.payment')),
            ],
        ),
    ]
