# Generated by Django 5.0.1 on 2025-03-13 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='content',
        ),
        migrations.AddField(
            model_name='badge',
            name='isUnlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='badge',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='badge',
            name='targetProgress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=0, upload_to='courses/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='isDownloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='progress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='totalExercises',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='totalLessons',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progress',
            name='completion_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='required_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='progress',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='core.course'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('progress', models.IntegerField(default=0)),
                ('exercise', models.ManyToManyField(related_name='chapter_exercise', to='core.exercise')),
                ('lessons', models.ManyToManyField(related_name='chapters_lesson', to='core.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='chapters',
            field=models.ManyToManyField(related_name='courses', to='core.chapter'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('correctAnswer', models.CharField(max_length=255)),
                ('choices', models.ManyToManyField(related_name='questions_choices', to='core.choice')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='questions',
            field=models.ManyToManyField(related_name='exercises_questions', to='core.question'),
        ),
    ]
